package com.example.weatherapi;

import static android.content.ContentValues.TAG;

import androidx.appcompat.app.AppCompatActivity;
import androidx.cardview.widget.CardView;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.w3c.dom.Text;

import java.io.StringReader;
import java.lang.reflect.Array;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;

public class MainActivity extends AppCompatActivity {
    Spinner city ;
    TextView temperature,cityView,pressureView,humidityView,maxView,minView;
    private  final String key = "d71a6c55c4d90de4a6b412bc759e9758";
    private final String url = "https://api.openweathermap.org/data/2.5/weather";
    DecimalFormat df = new DecimalFormat("#.##");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        String[] str=new String[]{  "Adilabad",
                "Agar Malwa",
                "Agra",
                "Ahmedabad",
                "Ahmednagar",
                "Aizawl",
                "Ajmer",
                "Akola",
                "Alappuzha",
                "Aligarh",
                "Alipurduar",
                "Alirajpur",
                "Allahabad",
                "Almora",
                "Alwar",
                "Ambala",
                "Ambedkar Nagar",
                "Amethi (Chatrapati Sahuji Mahraj Nagar)",
                "Amravati",
                "Amreli",
                "Amritsar",
                "Amroha (J.P. Nagar)",
                "Anand",
                "Anantapur",
                "Anantnag",
                "Angul",
                "Anjaw",
                "Anuppur",
                "Araria",
                "Aravalli",
                "Ariyalur",
                "Arwal",
                "Ashoknagar",
                "Auraiya",
                "Aurangabad (BH)",
                "Aurangabad (MH)",
                "Azamgarh",
                "Bagalkot",
                "Bageshwar",
                "Baghpat",
                "Bahraich",
                "Baksa",
                "Balaghat",
                "Balangir",
                "Balasore",
                "Ballari (Bellary)",
                "Ballia",
                "Balod",
                "Baloda Bazar",
                "Balrampur (CG)",
                "Balrampur,Uttar Pradesh",
                "Banaskantha (Palanpur)",
                "Banda",
                "Bandipore",
                "Banka",
                "Bankura",
                "Banswara",
                "Barabanki",
                "Baramulla",
                "Baran",
                "Bareilly",
                "Bargarh",
                "Barmer",
                "Barnala",
                "Barpeta",
                "Barwani",
                "Bastar",
                "Basti",
                "Bathinda",
                "Beed",
                "Begusarai",
                "Belagavi (Belgaum)",
                "Bemetara",
                "Bengaluru (Bangalore) Rural ",
                "Bengaluru (Bangalore) Urban ",
                "Betul",
                "Bhadohi",
                "Bhadradri Kothagudem",
                "Bhadrak",
                "Bhagalpur",
                "Bhandara",
                "Bharatpur",
                "Bharuch",
                "Bhavnagar",
                "Bhilwara",
                "Bhind",
                "Bhiwani",
                "Bhojpur",
                "Bhopal",
                "Bidar",
                "Bijapur",
                "Bijnor",
                "Bikaner",
                "Bilaspur (CG)",
                "Bilaspur (HP)",
                "Birbhum",
                "Bishnupur",
                "Biswanath",
                "Bokaro",
                "Bongaigaon",
                "Botad",
                "Boudh",
                "Budaun",
                "Budgam",
                "Bulandshahr",
                "Buldhana",
                "Bundi",
                "Burhanpur",
                "Buxar",
                "Cachar",
                "Central Delhi",
                "Chamarajanagar",
                "Chamba",
                "Chamoli",
                "Champawat",
                "Champhai",
                "Chandauli",
                "Chandel",
                "Chandigarh",
                "Chandrapur",
                "Changlang",
                "Charaideo",
                "Charkhi Dadri",
                "Chatra",
                "Chengalpattu",
                "Chennai",
                "Chhatarpur",
                "Chhindwara",
                "Chhota Udepur",
                "Chikballapur",
                "Chikkamagaluru (Chikmagalur) ",
                "Chirang",
                "Chitradurga",
                "Chitrakoot",
                "Chittoor",
                "Chittorgarh",
                "Churachandpur",
                "Churu",
                "Coimbatore",
                "Cooch Behar",
                "Cuddalore",
                "Cuttack",
                "Dadra & Nagar Haveli",
                "Dahod",
                "Dakshin Dinajpur (South Dinajpur) ",
                "Dakshina Kannada",
                "Daman",
                "Damoh",
                "Dangs (Ahwa)",
                "Dantewada (South Bastar)",
                "Darbhanga",
                "Darjeeling",
                "Darrang",
                "Datia",
                "Dausa",
                "Davangere",
                "Dehradun",
                "Deogarh",
                "Deoghar",
                "Deoria",
                "Devbhoomi Dwarka",
                "Dewas",
                "Dhalai",
                "Dhamtari",
                "Dhanbad",
                "Dhar",
                "Dharmapuri",
                "Dharwad",
                "Dhemaji",
                "Dhenkanal",
                "Dholpur",
                "Dhubri",
                "Dhule",
                "Dibang Valley",
                "Dibrugarh",
                "Dima Hasao (North Cachar Hills) ",
                "Dimapur",
                "Dindigul",
                "Dindori",
                "Diu",
                "Doda",
                "Dumka",
                "Dungarpur",
                "Durg",
                "East Champaran (Motihari)",
                "East Delhi",
                "East Garo Hills",
                "East Godavari",
                "East Jaintia Hills",
                "East Kameng",
                "East Khasi Hills",
                "East Siang",
                "East Sikkim",
                "East Singhbhum",
                "Ernakulam",
                "Erode",
                "Etah",
                "Etawah",
                "Faizabad",
                "Faridabad",
                "Faridkot",
                "Farrukhabad",
                "Fatehabad",
                "Fatehgarh Sahib",
                "Fatehpur",
                "Fazilka",
                "Ferozepur",
                "Firozabad",
                "Gadag",
                "Gadchiroli",
                "Gajapati",
                "Ganderbal",
                "Gandhinagar",
                "Ganjam",
                "Garhwa",
                "Gariyaband",
                "Gautam Buddha Nagar",
                "Gaya",
                "Ghaziabad",
                "Ghazipur",
                "Gir Somnath",
                "Giridih",
                "Goalpara",
                "Godda",
                "Golaghat",
                "Gomati",
                "Gonda",
                "Gondia",
                "Gopalganj",
                "Gorakhpur",
                "Gumla",
                "Guna",
                "Guntur",
                "Gurdaspur",
                "Gurugram (Gurgaon)",
                "Gwalior",
                "Hailakandi",
                "Hamirpur (HP)",
                "Hamirpur (UP)",
                "Hanumangarh",
                "Hapur (Panchsheel Nagar)",
                "Harda",
                "Hardoi",
                "Haridwar",
                "Hassan",
                "Hathras",
                "Haveri",
                "Hazaribag",
                "Hingoli",
                "Hisar",
                "Hojai",
                "Hooghly",
                "Hoshangabad",
                "Hoshiarpur",
                "Howrah",
                "Hyderabad",
                "Idukki",
                "Imphal East",
                "Imphal West",
                "Indore",
                "Jabalpur",
                "Jagatsinghapur",
                "Jagtial",
                "Jaipur",
                "Jaisalmer",
                "Jajpur",
                "Jalandhar",
                "Jalaun",
                "Jalgaon",
                "Jalna",
                "Jalore",
                "Jalpaiguri",
                "Jammu",
                "Jamnagar",
                "Jamtara",
                "Jamui",
                "Jangaon",
                "Janjgir-Champa",
                "Jashpur",
                "Jaunpur",
                "Jayashankar Bhoopalpally",
                "Jehanabad",
                "Jhabua",
                "Jhajjar",
                "Jhalawar",
                "Jhansi",
                "Jhargram",
                "Jharsuguda",
                "Jhunjhunu",
                "Jind",
                "Jiribam",
                "Jodhpur",
                "Jogulamba Gadwal",
                "Jorhat",
                "Junagadh",
                "Kabirdham (Kawardha)",
                "Kachchh",
                "Kaimur (Bhabua)",
                "Kaithal",
                "Kakching",
                "Kalaburagi (Gulbarga)",
                "Kalahandi",
                "Kalimpong",
                "Kallakurichi",
                "Kamareddy",
                "Kamjong",
                "Kamle",
                "Kamrup",
                "Kamrup Metropolitan",
                "Kanchipuram",
                "Kandhamal",
                "Kangpokpi",
                "Kangra",
                "Kanker (North Bastar)",
                "Kannauj",
                "Kannur",
                "Kanpur Dehat",
                "Kanpur Nagar",
                "Kanshiram Nagar (Kasganj)",
                "Kanyakumari",
                "Kapurthala",
                "Karaikal",
                "Karauli",
                "Karbi Anglong",
                "Kargil",
                "Karimganj",
                "Karimnagar",
                "Karnal",
                "Karur",
                "Kasaragod",
                "Kathua",
                "Katihar",
                "Katni",
                "Kaushambi",
                "Kendrapara",
                "Kendujhar (Keonjhar)",
                "Khagaria",
                "Khammam",
                "Khandwa",
                "Khargone",
                "Kheda (Nadiad)",
                "Khordha",
                "Khowai",
                "Khunti",
                "Kinnaur",
                "Kiphire",
                "Kishanganj",
                "Kishtwar",
                "Kodagu",
                "Koderma",
                "Kohima",
                "Kokrajhar",
                "Kolar",
                "Kolasib",
                "Kolhapur",
                "Kolkata",
                "Kollam",
                "Komaram Bheem Asifabad",
                "Kondagaon",
                "Koppal",
                "Koraput",
                "Korba",
                "Korea (Koriya)",
                "Kota",
                "Kottayam",
                "Kozhikode",
                "Kra Daadi",
                "Krishna",
                "Krishnagiri",
                "Kulgam",
                "Kullu",
                "Kupwara",
                "Kurnool",
                "Kurukshetra",
                "Kurung Kumey",
                "Kushinagar (Padrauna)",
                "Lahaul & Spiti",
                "Lakhimpur",
                "Lakhimpur - Kheri",
                "Lakhisarai",
                "Lakshadweep",
                "Lalitpur",
                "Latehar",
                "Latur",
                "Lawngtlai",
                "Leh",
                "Lepa Rada",
                "Lohardaga",
                "Lohit",
                "Longding",
                "Longleng",
                "Lower Dibang Valley",
                "Lower Siang",
                "Lower Subansiri",
                "Lucknow",
                "Ludhiana",
                "Lunglei",
                "Madhepura",
                "Madhubani",
                "Madurai",
                "Mahabubabad",
                "Mahabubnagar",
                "Maharajganj",
                "Mahasamund",
                "Mahe",
                "Mahendragarh",
                "Mahisagar",
                "Mahoba",
                "Mainpuri",
                "Majuli",
                "Malappuram",
                "Malda",
                "Malkangiri",
                "Mamit",
                "Mancherial",
                "Mandi",
                "Mandla",
                "Mandsaur",
                "Mandya",
                "Mansa",
                "Mathura",
                "Mau",
                "Mayurbhanj",
                "Medak",
                "Medchal",
                "Meerut",
                "Mehsana",
                "Mirzapur",
                "Moga",
                "Mokokchung",
                "Mon",
                "Moradabad",
                "Morbi",
                "Morena",
                "Morigaon",
                "Muktsar",
                "Mumbai City",
                "Mumbai Suburban",
                "Mungeli",
                "Munger (Monghyr)",
                "Murshidabad",
                "Muzaffarnagar",
                "Muzaffarpur",
                "Mysuru (Mysore)",
                "Nabarangpur",
                "Nadia",
                "Nagaon",
                "Nagapattinam",
                "Nagarkurnool",
                "Nagaur",
                "Nagpur",
                "Nainital",
                "Nalanda",
                "Nalbari",
                "Nalgonda",
                "Namakkal",
                "Namsai",
                "Nanded",
                "Nandurbar",
                "Narayanpur",
                "Narmada (Rajpipla)",
                "Narsinghpur",
                "Nashik",
                "Navsari",
                "Nawada",
                "Nawanshahr (Shahid Bhagat Singh Nagar)",
                "Nayagarh",
                "Neemuch",
                "New Delhi",
                "Nicobar",
                "Nilgiris",
                "Nirmal",
                "Nizamabad",
                "Noney",
                "North Parganas",
                "North Delhi",
                "North East Delhi",
                "North Garo Hills",
                "North Goa",
                "North Sikkim",
                "North Tripura",
                "North West Delhi",
                "North and Middle Andaman",
                "Nuapada",
                "Nuh",
                "Osmanabad",
                "Pakke Kessang",
                "Pakur",
                "Palakkad",
                "Palamu",
                "Palghar",
                "Pali",
                "Palwal",
                "Panchkula",
                "Panchmahal (Godhra)",
                "Panipat",
                "Panna",
                "Papum Pare",
                "Parbhani",
                "Paschim (West) Burdwan (Bardhaman) ",
                "Paschim Medinipur (West Medinipur) ",
                "Patan",
                "Pathanamthitta",
                "Pathankot",
                "Patiala",
                "Patna",
                "Pauri Garhwal",
                "Peddapalli",
                "Perambalur",
                "Peren",
                "Phek",
                "Pherzawl",
                "Pilibhit",
                "Pithoragarh",
                "Poonch",
                "Porbandar",
                "Prakasam",
                "Pratapgarh (RJ)",
                "Pratapgarh (UP)",
                "Puducherry",
                "Pudukkottai",
                "Pulwama",
                "Pune",
                "Purba Burdwan (Bardhaman)",
                "Purba Medinipur (East Medinipur) ",
                "Puri",
                "Purnia (Purnea)",
                "Purulia",
                "RaeBareli",
                "Raichur",
                "Raigad",
                "Raigarh",
                "Raipur",
                "Raisen",
                "Rajanna Sircilla",
                "Rajgarh",
                "Rajkot",
                "Rajnandgaon",
                "Rajouri",
                "Rajsamand",
                "Ramanagara",
                "Ramanathapuram",
                "Ramban",
                "Ramgarh",
                "Rampur",
                "Ranchi",
                "Rangareddy",
                "Ranipet",
                "Ratlam",
                "Ratnagiri",
                "Rayagada",
                "Reasi",
                "Rewa",
                "Rewari",
                "Ri Bhoi",
                "Rohtak",
                "Rohtas",
                "Rudraprayag",
                "Rupnagar",
                "S-Z",
                "Sabarkantha (Himmatnagar)",
                "Sagar",
                "Saharanpur",
                "Saharsa",
                "Sahibganj",
                "Sahibzada Ajit Singh Nagar (Mohali) ",
                "Saiha",
                "Salem",
                "Samastipur",
                "Samba",
                "Sambalpur",
                "Sambhal (Bhim Nagar)",
                "Sangareddy",
                "Sangli",
                "Sangrur",
                "Sant Kabir Nagar",
                "Saran",
                "Satara",
                "Satna",
                "Sawai Madhopur",
                "Sehore",
                "Senapati",
                "Seoni",
                "Sepahijala",
                "Seraikela-Kharsawan",
                "Serchhip",
                "Shahdara",
                "Shahdol",
                "Shahjahanpur",
                "Shajapur",
                "Shamali (Prabuddh Nagar)",
                "Sheikhpura",
                "Sheohar",
                "Sheopur",
                "Shi Yomi",
                "Shimla",
                "Shivamogga (Shimoga)",
                "Shivpuri",
                "Shopian",
                "Shravasti",
                "Siang",
                "Siddharth Nagar",
                "Siddipet",
                "Sidhi",
                "Sikar",
                "Simdega",
                "Sindhudurg",
                "Singrauli",
                "Sirmaur (Sirmour)",
                "Sirohi",
                "Sirsa",
                "Sitamarhi",
                "Sitapur",
                "Sivaganga",
                "Sivasagar",
                "Siwan",
                "Solan",
                "Solapur",
                "Sonbhadra",
                "Sonepur",
                "Sonipat",
                "Sonitpur",
                "South Parganas",
                "South Andaman",
                "South Delhi",
                "South East Delhi",
                "South Garo Hills",
                "South Goa",
                "South Salamara-Mankachar",
                "South Sikkim",
                "South Tripura",
                "South West Delhi",
                "South West Garo Hills",
                "South West Khasi Hills",
                "Sri Ganganagar",
                "Sri Potti Sriramulu Nellore ",
                "Srikakulam",
                "Srinagar",
                "Sukma",
                "Sultanpur",
                "Sundargarh",
                "Supaul",
                "Surajpur",
                "Surat",
                "Surendranagar",
                "Surguja",
                "Suryapet",
                "Tamenglong",
                "Tapi (Vyara)",
                "Tarn Taran",
                "Tawang",
                "Tehri Garhwal",
                "Tengnoupal",
                "Tenkasi",
                "Thane",
                "Thanjavur",
                "Theni",
                "Thiruvananthapuram",
                "Thoothukudi (Tuticorin)",
                "Thoubal",
                "Thrissur",
                "Tikamgarh",
                "Tinsukia",
                "Tirap",
                "Tiruchirappalli",
                "Tirunelveli",
                "Tirupathur",
                "Tiruppur",
                "Tiruvallur",
                "Tiruvannamalai",
                "Tiruvarur",
                "Tonk",
                "Tuensang",
                "Tumakuru (Tumkur)",
                "Udaipur",
                "Udalguri",
                "Udham Singh Nagar",
                "Udhampur",
                "Udupi",
                "Ujjain",
                "Ukhrul",
                "Umaria",
                "Una",
                "Unakoti",
                "Unnao",
                "Upper Siang",
                "Upper Subansiri",
                "Uttar Dinajpur (North Dinajpur) ",
                "Uttara Kannada (Karwar)",
                "Uttarkashi",
                "Vadodara",
                "Vaishali",
                "Valsad",
                "Varanasi",
                "Vellore",
                "Vidisha",
                "Vijayapura",
                "Vikarabad",
                "Viluppuram",
                "Virudhunagar",
                "Visakhapatnam",
                "Vizianagaram",
                "Wanaparthy",
                "Warangal (Rural)",
                "Warangal (Urban)",
                "Wardha",
                "Washim",
                "Wayanad",
                "West Champaran",
                "West Delhi",
                "West Garo Hills",
                "West Godavari",
                "West Jaintia Hills",
                "West Kameng",
                "West Karbi Anglong",
                "West Khasi Hills",
                "West Siang",
                "West Sikkim",
                "West Singhbhum",
                "West Tripura",
                "Wokha",
                "YSR District, Kadapa (Cuddapah) ",
                "Yadadri Bhuvanagiri",
                "Yadgir",
                "Yamunanagar",
                "Yanam",
                "Yavatmal",
                "Zunheboto"};


        city = findViewById(R.id.city);
        temperature = findViewById(R.id.temperature);
        cityView = findViewById(R.id.city_name);
        pressureView = findViewById(R.id.pressure);
        humidityView = findViewById(R.id.humidity);
        maxView =findViewById(R.id.sea_level);
        minView = findViewById(R.id.ground_level);
        ArrayList<String> arrayList =new ArrayList<>();
        arrayList.addAll(Arrays.asList(str));
        city.setAdapter(new ArrayAdapter<>(MainActivity.this, android.R.layout.simple_spinner_dropdown_item,arrayList));


    }

    public void getWeatherDetails(View view) {
        CardView cardView;
        cardView = findViewById(R.id.carview);
        cardView.setVisibility(View.VISIBLE);
        String tempUrl = "";
        String cityapi = city.getSelectedItem().toString();
        tempUrl = url+"?q="+cityapi+"&appid=d71a6c55c4d90de4a6b412bc759e9758";
        Log.d("newurl", "getWeatherDetails:" + tempUrl);

        StringRequest stringRequest = new StringRequest(Request.Method.GET,tempUrl, new Response.Listener<String>() {
            @Override
            public void onResponse(String response)
            {
                try {
                    JSONObject jsonResponse = new JSONObject(response);
                    JSONObject jsonObjectMain = jsonResponse.getJSONObject("main");
                    double temp = jsonObjectMain.getDouble("temp") - 273.15;
                    double temp_min = jsonObjectMain.getDouble("temp_min") - 273.15;
                    double temp_max = jsonObjectMain.getDouble("temp_max") - 273.15;
                    float pressure = jsonObjectMain.getInt("pressure");
                    int humidty = jsonObjectMain.getInt("humidity");



                    String setTemp=df.format(temp);
                    temperature.setText(setTemp + "°C");

                    String setMin = df.format(temp_min);
                    minView.setText("MinTemp: " + setMin + "°C");

                    String setMax = df.format(temp_max);
                    maxView.setText("MaxTemp: " + setMax + "°C");

                    String cityname = jsonResponse.getString("name");
                    cityView.setText("City: " + cityname);

                    pressureView.setText("Pressure: " + pressure + " hPa");
                    humidityView.setText("Humidity: "+ humidty + "%");


                } catch (JSONException e) {
                    e.printStackTrace();
                }

            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                Toast.makeText(getApplicationContext(),"error",Toast.LENGTH_SHORT).show();
            }
        });

        RequestQueue requestQueue = Volley.newRequestQueue(getApplicationContext());
        requestQueue.add(stringRequest);



    }
}